### PR TITLE
deprication fixes, bump Surepy, Changed file-structure

### PR DESCRIPTION
**Pull request by ChristophCaina**
Changelog:

- Changed file structure of repository (files are now in 'custom_components/sureha/'
- Added dutch translation from PR #56 
- Added german translation 
- Fixed deprication warnings Issue #55 
- Bump Surepy to 0.9.0

### CODE REVIEW

**Comment by ChristophCaina** [comment]
Hi @benleb - can you please check, if you can merge the PR with the new file structure?
And sorry for the messed up PR earlier... Haven't realized, that other changes were added to the PR :-(

**Comment by benleb** [comment]
np :) will test it this weekend on my setup and merge it if everything works! thanks! :)

**Comment by fenty17** [comment]
Hi - just wondering if this is going to get merged soon?

**Comment by benleb** [comment]
-> included in https://github.com/benleb/sureha/releases/tag/v0.5.0

**Pull request merged**
